version: "3"
services:
  edgedb:
    image: edgedb/edgedb
    container_name: edgedb
    environment:
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
    volumes:
      - "./dbschema:/dbschema"
      - "./edgedb-data:/var/lib/edgedb/data"
    ports:
      - "5656:5656"